[rocprofiler-sdk][CI] Add formatting for counter_defs.yaml file

diff --git a/.github/workflows/rocprofiler-sdk-formatting.yml b/.github/workflows/rocprofiler-sdk-formatting.yml
--- a/.github/workflows/rocprofiler-sdk-formatting.yml
+++ b/.github/workflows/rocprofiler-sdk-formatting.yml
@@ -175,3 +175,35 @@ jobs:
           cat ${OUTFILE}
           exit 1
         fi
+
+  counter_defs:
+    runs-on: ubuntu-22.04
+
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        sparse-checkout: projects/rocprofiler-sdk
+
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.10'
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        python -m pip install ruamel.yaml
+
+    - name: Ensure counter_defs.yaml is formatted
+      working-directory: projects/rocprofiler-sdk
+      run: |
+        python source/scripts/format-deps.py --counter-defs
+        if [ $(git diff -- source/share/rocprofiler-sdk/counter_defs.yaml | wc -l) -ne 0 ]; then
+          echo ""
+          echo "::error::YAML file is not properly formatted. Run the following command to fix:"
+          echo ""
+          echo "  cd projects/rocprofiler-sdk && python source/scripts/format-deps.py --counter-defs"
+          echo ""
+          git diff -- source/share/rocprofiler-sdk/counter_defs.yaml
+          exit 1
+        fi
